import = [
       #"~/.config/alacritty/catppuccin-frappe.toml"
       "~/.config/alacritty/catppuccin-macchiato.toml"
       #"~/.config/alacritty/catppuccin-mocha.toml"
]

# Font configuration
[font]

# Point size
size = 13.0

[window]
padding.x = 10
padding.y = 10

decorations = "ButtonLess"

opacity = 0.6
blur = true
