allow_hosts:
  - '\.jeoffrey\.me'
  - '\.obyw\.one'
  - '\.fj-studios\.eu'
  - '\.maya\.fit'
  - '\.shiki\.sh'
  - '\.shikki\.io'
  - '\.shikki\.app'
  - '\.moto-project\.org'
  - '\.flsh\.sh'
  - '\.getflsh\.app'